apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-registry-storage
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem